import React from "react";
import "./globals.css";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
// import Navbar from "../../Component/Navbar";
import PropTypes from "prop-types";
import Nvbrr from "../../Component/Nvbrr";
  
 const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Navbar /> */}

      <div className=" ">
        <Nvbrr />
 
        </div>
        <div className="all_Child">{children}</div>
  
      </body>
    </html>
  );
}

RootLayout.propTypes = {
  children: PropTypes.node.isRequired,
};
